# Generated by Django 5.1.1 on 2024-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturer_product_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out_for_delivery', 'out_for_delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
